"""Recently parsed projects: cached JSON, original .knxproj, notes, raw XML."""
import json
import zipfile
from datetime import datetime

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse, JSONResponse, Response

import core
from core import load_recent_projects, project_slug
from models import NotesUpdate

router = APIRouter(prefix="/api/recent-projects", tags=["recent-projects"])


def _validate_slug(slug: str) -> str:
    # Slugs are generated by project_slug(); anything else (e.g. URL-encoded
    # "../") must never reach the filesystem.
    if not slug or slug != project_slug(slug) or set(slug) <= {"."}:
        raise HTTPException(status_code=400, detail="Ungültiger Projektname")
    return slug


@router.get("")
def get_recent_projects():
    return JSONResponse(content=load_recent_projects())


@router.get("/notes")
def get_all_notes():
    result = {}
    for f in core.PROJECTS_DIR.glob("*.notes.md"):
        slug = f.stem[:-6]  # entferne ".notes"
        result[slug] = f.read_text(encoding="utf-8")
    return JSONResponse(result)


@router.post("/{slug}/notes")
async def save_notes(slug: str, data: NotesUpdate):
    _validate_slug(slug)
    p = core.PROJECTS_DIR / f"{slug}.json"
    if not p.exists():
        raise HTTPException(status_code=404, detail="Projekt nicht gefunden")
    (core.PROJECTS_DIR / f"{slug}.notes.md").write_text(data.text, encoding="utf-8")
    return {"ok": True}


@router.get("/{slug}/knxproj")
def get_recent_knxproj(slug: str):
    _validate_slug(slug)
    p = core.PROJECTS_DIR / f"{slug}.knxproj"
    if not p.exists():
        raise HTTPException(status_code=404, detail="Original nicht gespeichert")
    projects = load_recent_projects()
    meta = next((r for r in projects if r["slug"] == slug), {})
    filename = meta.get("filename", f"{slug}.knxproj")
    return FileResponse(str(p), media_type="application/octet-stream", filename=filename)


@router.get("/{slug}/xml")
def get_recent_xml(slug: str):
    _validate_slug(slug)
    p = core.PROJECTS_DIR / f"{slug}.knxproj"
    if not p.exists():
        raise HTTPException(status_code=404, detail="Original nicht gespeichert")
    with zipfile.ZipFile(str(p)) as zf:
        # Suche nach der Haupt-Projektdatei (0.xml oder ähnlich)
        xml_names = [n for n in zf.namelist() if n.endswith('.xml') and '/' not in n]
        if not xml_names:
            xml_names = [n for n in zf.namelist() if n.endswith('.xml')]
        if not xml_names:
            raise HTTPException(status_code=404, detail="Keine XML im Archiv")
        xml_content = zf.read(xml_names[0]).decode("utf-8", errors="replace")
    projects = load_recent_projects()
    meta = next((r for r in projects if r["slug"] == slug), {})
    filename = meta.get("filename", slug).replace(".knxproj", ".xml")
    return Response(content=xml_content, media_type="application/xml",
                    headers={"Content-Disposition": f'attachment; filename="{filename}"'})


@router.get("/{slug}/data")
def get_recent_project_data(slug: str):
    _validate_slug(slug)
    p = core.PROJECTS_DIR / f"{slug}.json"
    if not p.exists():
        raise HTTPException(status_code=404, detail="Not found")
    data = json.loads(p.read_text())
    # Update server state so DPT decoding works for incoming telegrams
    core.set_project_data(data)
    # Move to top with updated timestamp
    recent = load_recent_projects()
    entry = next((r for r in recent if r["slug"] == slug), None)
    if entry:
        entry["last_used"] = datetime.now().isoformat(timespec="seconds")
        recent = [entry] + [r for r in recent if r["slug"] != slug]
        core.RECENT_PROJECTS_PATH.write_text(json.dumps(recent, indent=2))
    return JSONResponse(content=data)


@router.get("/{slug}/raw")
def get_recent_project_raw(slug: str):
    _validate_slug(slug)
    p = core.PROJECTS_DIR / f"{slug}.json"
    if not p.exists():
        raise HTTPException(status_code=404, detail="Not found")
    return JSONResponse(content=json.loads(p.read_text()))


@router.delete("/{slug}")
def delete_recent_project(slug: str):
    _validate_slug(slug)
    recent = [r for r in load_recent_projects() if r["slug"] != slug]
    core.RECENT_PROJECTS_PATH.write_text(json.dumps(recent, indent=2))
    p = core.PROJECTS_DIR / f"{slug}.json"
    if p.exists():
        p.unlink()
    return {"ok": True}
